/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mapsforge_playground_JNITestMain */

#ifndef _Included_org_mapsforge_playground_JNITestMain
#define _Included_org_mapsforge_playground_JNITestMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mapsforge_playground_JNITestMain
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mapsforge_playground_JNITestMain_printHello
  (JNIEnv *, jclass);

/*
 * Class:     org_mapsforge_playground_JNITestMain
 * Method:    createTestPNG
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mapsforge_playground_JNITestMain_createTestPNG
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
